# Generated by Django 4.1 on 2022-08-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The datetime this was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The datetime this was updated')),
                ('name', models.TextField(help_text='Name of this product')),
                ('gtin', models.CharField(blank=True, default=None, help_text='GTIN of this product, if any', max_length=13, null=True, unique=True)),
                ('weight', models.PositiveIntegerField(help_text='In kg')),
                ('length', models.PositiveIntegerField(help_text='In mm')),
                ('height', models.PositiveIntegerField(help_text='In mm')),
                ('width', models.PositiveIntegerField(help_text='In mm')),
                ('image', models.URLField(blank=True, default=None, help_text='The image of this product, if any', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The datetime this was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The datetime this was updated')),
                ('quantity', models.PositiveIntegerField(help_text='Available quantity for this offer')),
                ('seller_price', models.DecimalField(decimal_places=2, help_text='The price for this offer from the seller', max_digits=12)),
                ('product', models.ForeignKey(help_text='The product this offer is for', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='product.product')),
                ('seller', models.ForeignKey(help_text='The seller from whom this offer is being made', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seller', 'product')},
            },
        ),
    ]
