# Generated by Django 4.1 on 2022-08-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The datetime this was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The datetime this was updated')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='The shipping costs associated with this order', max_digits=14)),
                ('vat', models.DecimalField(decimal_places=2, default=0, help_text='The VAT value of this order', max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='The subtotal represents the individual item value (excluding shipping costs, excluding VAT)', max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='The total value of this order', max_digits=14)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether or not this order has been placed or is still pending')),
                ('buyer', models.ForeignKey(help_text='The buyer that placed the order', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The datetime this was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The datetime this was updated')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity that has been ordered')),
                ('price', models.DecimalField(decimal_places=2, help_text='The accepted net price for this order line', max_digits=14)),
                ('order', models.ForeignKey(help_text='The order that this order line relates to', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.order')),
                ('product', models.ForeignKey(help_text='The product that is being purchased', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('seller', models.ForeignKey(help_text='The seller that is supplying this item', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
